import { createClient } from '@/lib/supabase/server';
import { ProductCard } from '@/components/ui/ProductCard';
import { SearchInput } from '@/components/ui/SearchInput';
import { CategoryPills } from '@/components/ui/CategoryPills';
import { signedProductImageUrls } from '@/lib/images/urls';
import Link from 'next/link';

export default async function CatalogPage({ searchParams }: { searchParams: Promise<{ q?: string; categoria?: string }> }) {
  const filters = await searchParams; const q = (filters.q || '').slice(0, 80).replace(/[^\p{L}\p{N}\s-]/gu, ' ').replace(/\s+/g, ' ').trim(); const categorySlug = filters.categoria || ''; const supabase = await createClient();
  const [{ data: categories }, { data: rawProducts, error }] = await Promise.all([
    supabase.from('categories').select('id,name,slug,display_order').eq('is_active', true).order('display_order'),
    supabase.from('products').select('id,name,slug,sku,barcode,price,unit,minimum_quantity,step_quantity,brand,featured,category_id,categories(name,slug),product_variants(id,name,sku,barcode,stock_quantity,sale_price,is_active),product_images(storage_path,is_primary)').eq('is_active', true).eq('product_images.is_primary', true).order('created_at', { ascending: false }),
  ]);
  const products = await Promise.all((rawProducts || []).filter((p: any) => { const c = Array.isArray(p.categories) ? p.categories[0] : p.categories; const variants = p.product_variants || []; const hay = `${p.name} ${p.brand || ''} ${p.sku || ''} ${p.barcode || ''} ${variants.map((v: any) => `${v.sku || ''} ${v.barcode || ''}`).join(' ')}`.toLocaleLowerCase(); return (!categorySlug || c?.slug === categorySlug) && (!q || hay.includes(q.toLocaleLowerCase())); }).map(async (p: any) => ({ ...p, product_images: await signedProductImageUrls(p.product_images || []) })));
  const featured = products.filter((p: any) => p.featured).slice(0, 8); const grouped = (categories || []).map((c: any) => ({ category: c, products: products.filter((p: any) => p.category_id === c.id).sort((a: any, b: any) => Number(Boolean(b.featured)) - Number(Boolean(a.featured))).slice(0, 8) })).filter((g) => g.products.length); const selectedCategory = (categories || []).find((c: any) => c.slug === categorySlug); const searchMode = Boolean(q || categorySlug);
  return <div className="mx-auto max-w-7xl space-y-8 px-4 py-8"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-2xl font-bold text-slate-900">{searchMode ? `Resultados para “${q || categorySlug}”` : 'Catálogo de produtos'}</h1><p className="text-sm text-slate-500">Encontre materiais para sua obra</p></div><SearchInput /></div>{categories && <CategoryPills categories={categories} />}{error ? <div className="rounded-xl bg-red-50 p-8 text-center text-red-700">Erro ao carregar os produtos do catálogo.</div> : searchMode ? <ProductGrid products={products} /> : <>{featured.length > 0 && <Section title="Destaques gerais"><ProductGrid products={featured} /></Section>}{grouped.map(({ category, products: items }) => <Section key={category.id} title={category.name} href={`/produtos?categoria=${category.slug}`}><ProductGrid products={items} /></Section>)}{featured.length === 0 && grouped.length === 0 && <Empty />}</>}</div>;
}
function Section({ title, href, children }: { title: string; href?: string; children: React.ReactNode }) { return <section className="space-y-3"><div className="flex items-center justify-between border-b border-slate-200 pb-2"><h2 className="text-lg font-bold uppercase tracking-wide text-slate-800">{title}</h2>{href && <Link href={href} className="text-sm font-semibold text-amber-700 hover:underline">Ver todos →</Link>}</div>{children}</section>; }
function ProductGrid({ products }: { products: any[] }) { return products.length ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{products.map((product) => <ProductCard key={product.id} product={product} compact featured={Boolean(product.featured)} />)}</div> : <Empty />; }
function Empty() { return <div className="rounded-xl border border-dashed p-12 text-center text-slate-500">Nenhum produto encontrado.</div>; }
